baseURL: "https://zero.shotlearni.ng/"
languageCode: en-us
title: kimh
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 20
    - identifier: cv
      name: CV
      url: /cv/
      weight: 30
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 40

params:
  env: production
  images: ["img/og.png"]
  defaultTheme: light
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowReadingTime: false
  ShowPostNavLinks: false
  ShowShareButtons: false
  hideMeta: false
  hideDescriptionInList: false
  assets:
    disableHLJS: true

markup:
  goldmark:
    renderer:
      unsafe: true
    extensions:
      passthrough:
        enable: true
        delimiters:
          block:
            - ["$$", "$$"]
            - ["\\[", "\\]"]
          inline:
            - ["$", "$"]
            - ["\\(", "\\)"]
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    tabWidth: 2

taxonomies:
  tag: tags

outputs:
  home:
    - HTML
    - RSS
