name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: write

jobs:
  build:
    if: github.ref != 'refs/heads/gh-pages'
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Hugo
        run: |
          curl -L -o /tmp/hugo.tar.gz 'https://github.com/gohugoio/hugo/releases/download/v0.110.0/hugo_extended_0.110.0_linux-amd64.tar.gz'
          tar -C /usr/local/bin --strip-components=1 -zxvf /tmp/hugo.tar.gz hugo_extended_0.110.0_linux-amd64/hugo

      - name: Verify Hugo Installation
        run: hugo version

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: |
          touch public/.nojekyll
          git clone --depth 1 --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dev-mhyun/blog.git built-site
          cp -R public/* built-site/
          cd built-site
          git add .
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -m 'Updated site' || echo "No changes to commit"
          git push origin gh-pages
