name: Build & Deploy
on:
  push:
    branches:
      - main  # 변경 필요: 주 브랜치 기준으로 빌드 (gh-pages 제외)
  pull_request:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Hugo
        run: |
          HUGO_VERSION=0.110.0
          curl -L -o /tmp/hugo.tar.gz "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.tar.gz"
          tar -zxvf /tmp/hugo.tar.gz -C /tmp
          mv /tmp/hugo /usr/local/bin/hugo

      - name: Verify Hugo Installation
        run: hugo version

      - name: Build
        run: hugo --minify

      - name: Deploy
        run: |
          touch public/.nojekyll
          git clone --depth 1 --branch gh-pages https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/dev-mhyun/blog.git built-site
          rsync -av --delete public/ built-site/
          cd built-site
          git add .
          if ! git diff --cached --exit-code; then
            git config user.name 'github-actions[bot]'
            git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git commit -m 'Updated site'
            git push origin gh-pages
          else
            echo "No changes to commit"
          fi
